language: php

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

# be polite; keep the cached packages
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: vendor/bin/phpunit

notifications:
  email: false
