language: php

services:
  - mysql

sudo: false

env:
  global:
    - coverage=no

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: coverage=yes
  allow_failures:
    - env: coverage=yes

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mysql -e "CREATE DATABASE jaal; CREATE USER 'jaal'@'localhost'; GRANT ALL PRIVILEGES ON jaal . * TO 'jaal'@'localhost'; FLUSH PRIVILEGES;"

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - if [[ $coverage = 'yes' ]]; then vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $coverage = 'no' ]]; then vendor/bin/phpunit -c phpunit.xml; fi

after_script:
  - if [[ $coverage = 'yes' ]]; then vendor/bin/php-coveralls -v; fi

notifications:
  email: false
